export const ADD_DETAILS = 'ADD_DETAILS';
export const FETCH_DICE_HISTORY = 'FETCH_DICE_HISTORY';
export const UPDATE_DICE_HISTORY = 'UPDATE_DICE_HISTORY';
export const UPDATE_PLAYER_DETAILS = 'UPDATE_PLAYER_DETAILS';
export const FETCH_PLAYER_DETAIL = 'FETCH_PLAYER_DETAIL';